### PR TITLE
fix(config): resolve `<rootDir>` to `.` in `coverageDirectory`

### LINKED ISSUE #22: Minor Bug: `coverageDirectory` set to `"<rootDir>/coverage"` results in Error: `ENOENT: no such file or directory`
Hi @rbardini 

This is a useful plugin, thank you!

I noticed that configuring `coverageDirectory` to be `coverageDirectory: "<rootDir>/coverage"` results in an `ENOENT` error because [<rootDir>](https://jestjs.io/docs/configuration#rootdir-string) is not parsed. The following value works `"./coverage"`.

Regards,
TJ

### PR DESCRIPTION
**Pull request by anlesk**
Jest allows root directory `<rootDir>` string token to be specified for path configurations.
This fix allows this variable to be resolved into `path.dirname(configPath)`.

Fixes #22

### CODE REVIEW

File: lib/getData.js [hunk 1]
```diff
@@ -7,9 +7,9 @@ const getData = async configPath => {
     coverageThreshold: { global: thresholds },
     coverageDirectory = 'coverage',
   } = typeof config === 'function' ? await config() : config
+  const normalizedCoverageDirectory = coverageDirectory.replace('<rootDir>', path.dirname(configPath))
   const reportPath = path.resolve(
-    path.dirname(configPath),
-    coverageDirectory,
+    normalizedCoverageDirectory,
```
Comment (rbardini) [inline lib/getData.js:12]: Will this also work if `coverageDirectory` does _not_ contain `<rootDir>`?

Comment (anlesk) [reply lib/getData.js:12]: @rbardini, of course. In case path does not contain `<rootDir>`, the path will be used as is (no substitutions).

Comment (anlesk) [reply lib/getData.js]: I can add a test for that if you want

Comment (rbardini) [reply lib/getData.js]: When `coverageDirectory` does not contain `<rootDir>`, the change will be equivalent to:

```diff
 const reportPath = path.resolve(
-  path.dirname(configPath),
   coverageDirectory,
   'coverage-summary.json',
 )
```

I wonder if `resolvePath` will still resolve correctly without `configPath`.

What if we simply replaced `<rootDir>` with the current directory? Something like:

```diff
 const reportPath = path.resolve(
   path.dirname(configPath),
-  coverageDirectory,
+  coverageDirectory.replace('<rootDir>', '.'),
   'coverage-summary.json',
 )
```

Comment (anlesk) [reply lib/getData.js]: I see, yeah. You are right - let me work on tests as well.
Since the code tries to resolve the `coverage-summary.json` from the config path dir - this should work.

Comment (anlesk) [reply lib/getData.js]: @rbardini done

**Comment by anlesk** [comment]
@rbardini kindly review / approve the workflow run.

**Comment by rbardini** [comment]
Thanks for the fix, @anlesk! This solves the default use case, but eventually we should resolve `<rootDir>` to the [`rootDir`](https://jestjs.io/docs/configuration#rootdir-string) option set in the Jest config, maybe using Jest's [`replaceRootDirInPath`](https://github.com/jestjs/jest/blob/bd1c6db7c15c23788ca3e09c919138e48dd3b28a/packages/jest-config/src/utils.ts#L57-L69) util.

**Comment by anlesk** [comment]
@rbardini, I agree. The code assumes that root directory is where config file is located, but should take other options into account.
